name: food_classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - numpy=1.19.2
  - pandas=1.1.5
  - matplotlib=3.3.4
  - seaborn=0.11.2
  - scikit-learn=0.24.1
  - tensorflow=2.2.0
  - flask=1.1.2
  - waitress=2.0.0